# Generated by Django 5.2.3 on 2025-06-11 20:34

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_circadiano', '0002_comentario'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='articulo',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='articulos_liked', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='comentario',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='comentarios_liked', to=settings.AUTH_USER_MODEL),
        ),
    ]
