# Generated by Django 5.2.3 on 2025-06-12 12:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_circadiano', '0004_categoria_etiqueta'),
    ]

    operations = [
        migrations.AddField(
            model_name='articulo',
            name='categoria',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='articulos', to='blog_circadiano.categoria'),
        ),
        migrations.AddField(
            model_name='articulo',
            name='etiquetas',
            field=models.ManyToManyField(blank=True, related_name='articulos', to='blog_circadiano.etiqueta'),
        ),
    ]
