# Generated by Django 5.2.3 on 2025-06-19 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_circadiano', '0005_articulo_categoria_articulo_etiquetas'),
    ]

    operations = [
        migrations.AddField(
            model_name='articulo',
            name='guia_slug',
            field=models.CharField(blank=True, help_text="Nombre del archivo HTML de la guía interactiva en la carpeta de plantillas (ej: 'guia-inversion.html').", max_length=100, null=True, unique=True),
        ),
    ]
