# Generated by Django 5.2.3 on 2025-06-23 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_circadiano', '0006_articulo_guia_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='articulo',
            name='google_doc_id',
            field=models.CharField(blank=True, help_text='El ID del documento de Google Docs para incrustar.', max_length=150, null=True),
        ),
    ]
