# Generated by Django 5.2.3 on 2025-06-23 21:25

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog_circadiano', '0007_articulo_google_doc_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='articulo',
            name='google_doc_id',
        ),
        migrations.AddField(
            model_name='articulo',
            name='documento_detallado',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='Documento Detallado (Investigación)'),
        ),
    ]
