# Generated by Django 5.2.3 on 2025-06-25 16:32

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog_circadiano', '0008_remove_articulo_google_doc_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articulo',
            name='contenido',
            field=ckeditor_uploader.fields.RichTextUploadingField(verbose_name='Contenido Principal'),
        ),
    ]
