# Generated by Django 5.2.3 on 2025-07-01 00:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_circadiano', '0009_alter_articulo_contenido'),
    ]

    operations = [
        migrations.CreateModel(
            name='Serie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=200, unique=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('imagen_destacada', models.ImageField(blank=True, null=True, upload_to='series/')),
            ],
            options={
                'verbose_name_plural': 'Series',
                'ordering': ['titulo'],
            },
        ),
        migrations.AddField(
            model_name='articulo',
            name='serie',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='articulos', to='blog_circadiano.serie'),
        ),
    ]
